### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by jerodev** [jerodev/TableTopFinder-lang#1]
Translate language files to the German language

- [x] common.php
- [x] email.php
- [x] keywords.php
- [x] layout.php
- [x] pagination.php
- [x] passwords.php
- [x] validation.php
- [x] auth.php
- [x] pages/boardgames.php
- [x] pages/home.php
- [x] pages/info.php

**Comment by padarom** [comment]
German has a formal and an informal form of "You". Most websites targeted at individuals rather than businesses use the informal form because it's more personal. I assume that's what you'd want too?

**Comment by jerodev** [comment]
Indeed, Dutch has the same thing and I used the informal form for these translations.
