### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by jerodev** [jerodev/TableTopFinder-lang#2]
Translate language files to the Spanish language

- [x] common.php
- [x] email.php
- [x] keywords.php
- [x] layout.php
- [x] pagination.php
- [x] passwords.php
- [x] auth.php
- [x] pages/boardgames.php
- [x] pages/home.php
- [x] pages/info.php

**Comment by damiansire** [comment]
I will begin to translate to Spanish.
Comenzare a traducirla a español

**Comment by paoga87** [comment]
I can help with the Spanish translations. What exactly needs to be translated and how do I get started?

**Comment by gonzalovilaseca** [comment]
Can help too

**Comment by wolframtheta** [comment]
I will take the email.php and do the spanish translation
