### ISSUE TITLE
Translate to Italian

### ISSUE THREAD

**Issue by jerodev** [jerodev/TableTopFinder-lang#3]
Translate language files to the Italian language

- [x] common.php
- [x] email.php
- [x] keywords.php
- [x] layout.php
- [x] pagination.php
- [x] passwords.php
- [x] auth.php
- [x] pages/boardgames.php
- [x] pages/home.php
- [x] pages/info.php

**Comment by ludoro** [comment]
Hello. I would love to tackle this one, but I do not understand what I need to do: I went to src/it/validation.php but It seems that everything has already a translation. What am I missing?

**Comment by jerodev** [comment]
Hi, the `validation.php` files have already been translated for all languages. The other files can be copied from [the English language folder](https://github.com/jerodev/TableTopFinder-lang/tree/master/src/en).
